export const mailClassifications = [
  {
    category: 'Pendidikan dan Pelatihan (DL)',
    items: [
      { name: 'Pendidikan Pelatihan', code: 'DL1' },
      { name: 'Beasiswa', code: 'DL1.1' },
      { name: 'Sosialisasi, Bimbingan Teknis, Konsultasi, Dan Asistensi', code: 'DL1.10' },
      { name: 'Perencanaan Pembelajaran dan Pengembangan Program', code: 'DL1.3' },
      { name: 'Kurikulum dan Silabus', code: 'DL1.4' },
      { name: 'Tenaga Pengajar', code: 'DL1.5' },
      { name: 'Penyelenggaraan Pembelajaran', code: 'DL1.6' },
      { name: 'Evaluasi Pembelajaran', code: 'DL1.7' },
      { name: 'Monitoring dan Evaluasi Program Pembelajaran', code: 'DL1.8' },
      { name: 'Penerbitan Surat Keterangan Pembelajaran', code: 'DL1.9' },
    ],
  },
  {
    category: 'Hukum (HK)',
    items: [
      { name: 'Peraturan Perundang-undangan Eksternal', code: 'HK1.1' },
      { name: 'Undang-Undang/Perppu', code: 'HK1.1.1' },
      { name: 'Peraturan Pemerintah', code: 'HK1.1.2' },
      { name: 'Keputusan Presiden', code: 'HK1.1.4' },
      { name: 'Instruksi Presiden', code: 'HK1.1.5' },
      { name: 'Peraturan Perundang-undangan/Kebijakan Internal', code: 'HK1.2' },
      { name: 'Peraturan Mahkamah Agung', code: 'HK1.2.1' },
      { name: 'Instruksi', code: 'HK1.2.2' },
      { name: 'Surat Edaran', code: 'HK1.2.3' },
      { name: 'Maklumat Ketua Mahkamah Agung', code: 'HK1.2.4' },
      { name: 'Surat Perjanjian/Nota Kesepahaman', code: 'HK1.3' },
      { name: 'Dalam Negeri', code: 'HK1.3.1' },
      { name: 'Luar Negeri', code: 'HK1.3.2' },
      { name: 'Penyelesaian Perkara', code: 'HK2' },
      { name: 'Pidana Umum', code: 'HK2.1' },
      { name: 'Pidana Khusus', code: 'HK2.2' },
      { name: 'Pidana Militer', code: 'HK2.3' },
      { name: 'Perdata Umum', code: 'HK2.4' },
      { name: 'Perdata Niaga', code: 'HK2.5' },
      { name: 'Perdata Agama', code: 'HK2.6' },
      { name: 'Tata Usaha Negara', code: 'HK2.7' },
    ],
  },
  {
    category: 'Humas dan Protokol (HM)',
    items: [
      { name: 'Hubungan Masyarakat', code: 'HM1' },
      { name: 'Publikasi Informasi', code: 'HM1.1' },
      { name: 'Penerangan dan Publikasi', code: 'HM1.1.1' },
      { name: 'Pidato', code: 'HM1.1.2' },
      { name: 'Dokumentasi dan Peliputan', code: 'HM1.2' },
      { name: 'Hubungan Kelembagaan', code: 'HM2' },
      { name: 'Hubungan Antar Lembaga', code: 'HM2.1' },
      { name: 'Lembaga Pemerintah', code: 'HM2.1.1' },
      { name: 'Lembaga Swasta', code: 'HM2.1.2' },
      { name: 'Organisasi Sosial/LSM', code: 'HM2.1.3' },
      { name: 'Perguruan Tinggi', code: 'HM2.1.4' },
      { name: 'Keprotokolan', code: 'HM3' },
      { name: 'Upacara dan Kegiatan Resmi', code: 'HM3.1' },
      { name: 'Upacara/Acara Kedinasan', code: 'HM3.1.1' },
      { name: 'Kunjungan Dinas', code: 'HM3.1.2' },
      { name: 'Agenda Pimpinan', code: 'HM3.1.3' },
    ],
  },
  {
    category: 'Kearsipan (KA)',
    items: [
      { name: 'Kendali Arsip', code: 'KA1' },
      { name: 'Pengendalian dan Pengurusan Arsip', code: 'KA1.1' },
      { name: 'Layanan Penggunaan Arsip', code: 'KA1.2' },
      { name: 'Pengelolaan Arsip', code: 'KA2' },
      { name: 'Penyimpanan dan Pemeliharaan Arsip', code: 'KA2.1' },
      { name: 'Pengelolaan Arsip Aktif', code: 'KA2.1.1' },
      { name: 'Pengelolaan Arsip Inaktif', code: 'KA2.1.2' },
      { name: 'Pengelolaan Arsip Vital', code: 'KA2.1.3' },
      { name: 'Pengelolaan Arsip Terjaga', code: 'KA2.1.4' },
      { name: 'Perawatan Arsip', code: 'KA2.1.5' },
      { name: 'Penyelamatan dan Pemulihan Arsip', code: 'KA2.1.6' },
      { name: 'Penyusutan Arsip', code: 'KA2.2' },
      { name: 'Pemindahan Arsip Inaktif', code: 'KA2.2.1' },
      { name: 'Pemusnahan Arsip', code: 'KA2.2.2' },
      { name: 'Penyerahan Arsip', code: 'KA2.2.3' },
    ],
  },
  {
    category: 'Kepegawaian (KP)',
    items: [
      { name: 'Pengadaan SDM', code: 'KP1' },
      { name: 'Perencanaan dan Seleksi', code: 'KP1.1' },
      { name: 'Hakim Agung', code: 'KP1.1.1' },
      { name: 'Hakim', code: 'KP1.1.2' },
      { name: 'Hakim Ad Hoc', code: 'KP1.1.3' },
      { name: 'Pejabat Pimpinan Tinggi Pratama', code: 'KP1.1.5' },
      { name: 'PNS', code: 'KP1.1.6' },
      { name: 'PPPK', code: 'KP1.1.7' },
      { name: 'Tenaga Ahli dan Lain-lain', code: 'KP1.1.8' },
      { name: 'Pengangkatan', code: 'KP1.2' },
      { name: 'Hakim Agung', code: 'KP1.2.1' },
      { name: 'Hakim', code: 'KP1.2.2' },
      { name: 'Hakim Ad Hoc', code: 'KP1.2.3' },
      { name: 'Pejabat Pimpinan Tinggi Madya', code: 'KP1.2.4' },
      { name: 'Pejabat Pimpinan Tinggi Pratama', code: 'KP1.2.5' },
      { name: 'PNS', code: 'KP1.2.6' },
      { name: 'PPPK', code: 'KP1.2.7' },
      { name: 'Tenaga Ahli dan Lain-lain', code: 'KP1.2.8' },
      { name: 'Pegawai Pindah Instansi Masuk/Keluar', code: 'KP1.2.9' },
      { name: 'Kepangkatan', code: 'KP2' },
      { name: 'Kenaikan Pangkat/Golongan', code: 'KP2.1.1' },
      { name: 'Kenaikan Gaji Berkala', code: 'KP2.1.2' },
      { name: 'Penyesuaian Masa Kerja', code: 'KP2.1.3' },
      { name: 'Pengelolaan Kompetensi dan Manajemen Kinerja', code: 'KP3' },
      { name: 'Standar Kompetensi Jabatan', code: 'KP3.1' },
      { name: 'Standar Kompetensi Teknis Jabatan', code: 'KP3.1.1' },
      { name: 'Asesmen SDM', code: 'KP3.1.2' },
      { name: 'Profiling Pegawai', code: 'KP3.1.3' },
      { name: 'Ujian Kenaikan Pangkat/Ijazah', code: 'KP3.2' },
      { name: 'Ujian Penyesuaian Ijazah', code: 'KP3.2.1' },
      { name: 'Ujian Dinas', code: 'KP3.2.2' },
      { name: 'Ujian Kompetensi', code: 'KP3.2.3' },
      { name: 'Tugas Belajar/Izin Belajar', code: 'KP3.3' },
      { name: 'Tugas Belajar', code: 'KP3.3.1' },
      { name: 'Manajemen Kinerja Pegawai', code: 'KP3.4' },
      { name: 'Perencanaan dan Pelaksanaan Kinerja', code: 'KP3.4.1' },
      { name: 'Pembinaan Kinerja Pegawai', code: 'KP3.4.2' },
      { name: 'Evaluasi Kinerja Pegawai', code: 'KP3.4.3' },
      { name: 'Penetapan Jabatan dan Peringkat Pegawai', code: 'KP3.4.5' },
      { name: 'Pemetaan Pegawai', code: 'KP3.4.6' },
      { name: 'Manajemen Karier', code: 'KP4' },
      { name: 'Pengembangan Karier', code: 'KP4.1' },
      { name: 'Pengembangan Karier Pegawai', code: 'KP4.1.1' },
      { name: 'Manajemen Talenta', code: 'KP4.1.2' },
      { name: 'Mutasi, Promosi, dan Demasi', code: 'KP4.1.3' },
      { name: 'Tim Penilai Kinerja Jabatan', code: 'KP4.1.4' },
      { name: 'Pemberhentian Jabatan', code: 'KP4.1.5' },
      { name: 'Kesejahteraan Pegawai', code: 'KP5' },
      { name: 'Mutasi Keluarga', code: 'KP5.1' },
      { name: 'Layanan Kesehatan', code: 'KP5.2' },
      { name: 'Cuti dan Izin Bepergian ke Luar Negeri', code: 'KP5.3' },
      { name: 'Kegiatan Sosial', code: 'KP5.4' },
      { name: 'Koperasi', code: 'KP5.6' },
      { name: 'Transportasi Antar Jemput', code: 'KP5.7' },
      { name: 'Penghargaan dan Tanda Jasa', code: 'KP5.8' },
      { name: 'Pemberhentian Pegawai', code: 'KP6' },
      { name: 'Pemberhentian dengan Hak Pensiun', code: 'KP6.1' },
      { name: 'Pemberhentian tanpa Hak Pensiun', code: 'KP6.2' },
      { name: 'Tewas, Hilang/Meninggal dalam Tugas', code: 'KP6.3' },
      { name: 'Pembinaan Mental, Agama dan Konseling', code: 'KP6.4' },
      { name: 'Administrasi SDM', code: 'KP7' },
      { name: 'Pelaksanaan Tugas dalam Jabatan', code: 'KP7.1' },
      { name: 'Dokumentasi Identitas Pegawai', code: 'KP7.2' },
      { name: 'Laporan Pajak (LP2P) dan LHK', code: 'KP7.3' },
      { name: 'Penunjukan Plt/Plh', code: 'KP7.4' },
      { name: 'Izin Perkawinan/Perceraian Pegawai', code: 'KP7.5' },
      { name: 'Kode Etik dan Disiplin', code: 'KP8' },
      { name: 'Kode Etik dan Perilaku', code: 'KP8.1' },
      { name: 'Sanksi/Hukuman Disiplin', code: 'KP8.2' },
      { name: 'Penyelesaian Keberatan/Banding', code: 'KP8.3' },
      { name: 'Pemberhentian Berdasarkan Permasalahan Lainnya', code: 'KP8.4' },
    ],
  },
  {
    category: 'Pelaksanaan Anggaran (KU)',
    items: [
      { name: 'Pelaksanaan Anggaran dan Pertanggungjawaban', code: 'KU1' },
      { name: 'Perbendaharaan', code: 'KU1.1' },
      { name: 'Penetapan PA, KPA, PPK, Bendahara', code: 'KU1.1.1' },
      { name: 'Dokumen Pertanggungjawaban APBN', code: 'KU1.1.2' },
      { name: 'Laporan Pembayaran dan Pertanggungjawaban APBN', code: 'KU1.1.3' },
      { name: 'Asistensi Pelaksanaan Anggaran', code: 'KU1.1.4' },
      { name: 'Data Rekening BUN', code: 'KU1.1.5' },
      { name: 'Laporan Perkembangan Penyelesaian Kerugian Negara', code: 'KU1.2' },
      { name: 'Pelaksanaan Tuntutan Ganti Rugi', code: 'KU1.3' },
      { name: 'Penerimaan Negara Bukan Pajak', code: 'KU1.4' },
      { name: 'Pelaporan', code: 'KU2' },
      { name: 'Penyusunan Laporan Keuangan', code: 'KU2.1' },
      { name: 'Rekonsiliasi Laporan Keuangan', code: 'KU2.2' },
    ],
  },
  {
    category: 'Ortala (OT)',
    items: [
      { name: 'Organisasi dan Tatalaksana', code: 'OT1' },
      { name: 'Pembentukan/Perubahan/Penghapusan Organisasi', code: 'OT1.1' },
      { name: 'Tatalaksana/Mekanisme Kerja', code: 'OT1.2' },
      { name: 'Analisis Jabatan dan Analisis Beban Kerja', code: 'OT1.3' },
      { name: 'Evaluasi Jabatan', code: 'OT1.4' },
      { name: 'Peta Jabatan', code: 'OT1.5' },
      { name: 'Kinerja Organisasi', code: 'OT1.6' },
      { name: 'Penilaian Maturitas SPIP', code: 'OT1.7' },
    ],
  },
  {
    category: 'Perlengkapan (PL)',
    items: [
      { name: 'Pengadaan, Pengelolaan dan Penatausahaan BMN', code: 'PL1' },
      { name: 'Pengadaan Barang/Jasa', code: 'PL1.1' },
      { name: 'Pengadaan Barang Persediaan', code: 'PL1.1.1' },
      { name: 'Pengadaan Barang Inventaris', code: 'PL1.1.2' },
      { name: 'Pengadaan Barang', code: 'PL1.1.3' },
      { name: 'Pengadaan Jasa', code: 'PL1.1.4' },
      { name: 'Pengadaan Jasa Konsultansi', code: 'PL1.1.5' },
      { name: 'Pengadaan Jasa Lainnya', code: 'PL1.1.6' },
      { name: 'Pengadaan Jasa Konstruksi', code: 'PL1.1.7' },
      { name: 'Pengelolaan dan Penatausahaan BMN', code: 'PL1.2' },
      { name: 'Perencanaan BMN', code: 'PL1.2.1' },
      { name: 'Standar Barang dan Standar Kebutuhan BMN (SBSK)', code: 'PL1.2.2' },
      { name: 'Penghapusan dan Pemusnahan BMN', code: 'PL1.2.3' },
      { name: 'Hibah', code: 'PL1.2.4' },
      { name: 'Pencatatan BMN', code: 'PL1.2.5' },
      { name: 'Revaluasi dan Rekonsiliasi BMN', code: 'PL1.2.6' },
      { name: 'Pelaporan BMN', code: 'PL1.2.7' },
    ],
  },
  {
    category: 'Perpustakaan (PS)',
    items: [
      { name: 'Akuisisi Koleksi/Bahan Pustaka', code: 'PS1.1' },
      { name: 'Hibah Koleksi/Bahan Pustaka', code: 'PS1.2' },
      { name: 'Layanan Kepustakaan', code: 'PS1.3' },
      { name: 'Keanggotaan Perpustakaan', code: 'PS1.4' },
      { name: 'Form Keanggotaan Perpustakaan', code: 'PS1.4.1' },
      { name: 'Data Anggota Perpustakaan', code: 'PS1.4.2' },
      { name: 'Sirkulasi Koleksi/Bahan Pustaka', code: 'PS1.5' },
      { name: 'Preservasi Koleksi/Bahan Pustaka', code: 'PS1.6' },
      { name: 'Pengembangan Perpustakaan dan Minat Baca', code: 'PS1.7' },
    ],
  },
  {
    category: 'Pengawasan (PW)',
    items: [
      { name: 'Pengawasan/Pemantauan Internal', code: 'PW1' },
      { name: 'Pengawasan dengan Tindak Lanjut', code: 'PW1.1' },
      { name: 'Pengawasan/Pemantauan yang Memerlukan Tindak Lanjut', code: 'PW1.1.1' },
      { name: 'Pengawasan/Pemantauan dengan Unsur Pelanggaran Non Administratif/Fraud', code: 'PW1.1.2' },
      { name: 'Pengawasan yang Tidak Memerlukan Tindak Lanjut', code: 'PW1.2' },
      { name: 'Pengawasan/Pemantauan yang Tidak Memerlukan Tindak Lanjut', code: 'PW1.2.1' },
      { name: 'Pengawasan/Pemantauan dengan Unsur Pelanggaran Non Administratif/Fraud (Tidak Lanjut)', code: 'PW1.2.2' },
      { name: 'Pengawasan/Pemantauan Pegawai', code: 'PW1.3' },
      { name: 'Pengawasan Eksternal', code: 'PW1.4' },
    ],
  },
  {
    category: 'Perencanaan Anggaran (RA)',
    items: [
      { name: 'Perencanaan Anggaran', code: 'RA1' },
      { name: 'Penyusunan Rencana Program', code: 'RA1.1' },
      { name: 'Perjanjian Kinerja Tahunan (PKT)', code: 'RA1.10' },
      { name: 'Rencana Jangka Panjang Strategis', code: 'RA1.2' },
      { name: 'Rencana Kerja Strategis (RENSTRA)', code: 'RA1.3' },
      { name: 'Perencanaan Lintas Kementerian/Lembaga', code: 'RA1.4' },
      { name: 'Rencana Kerja (RENJA)', code: 'RA1.5' },
      { name: 'Usulan Anggaran', code: 'RA1.6' },
      { name: 'Penyusunan Anggaran', code: 'RA1.7' },
      { name: 'Revisi Anggaran', code: 'RA1.8' },
      { name: 'Rencana Kinerja Tahunan (RKT)', code: 'RA1.9' },
    ],
  },
  {
    category: 'Rumah Tangga (RT)',
    items: [
      { name: 'Penggunaan Gedung dan Fasilitas Kantor', code: 'RT1' },
      { name: 'Bangunan Gedung dan Lingkungan', code: 'RT1.1.1' },
      { name: 'Peralatan Operasional', code: 'RT1.1.2' },
      { name: 'Mekanikal Elektrikal', code: 'RT1.1.3' },
      { name: 'Ketertiban dan Keamanan', code: 'RT1.1.4' },
      { name: 'Pengelolaan Parkir', code: 'RT1.1.5' },
      { name: 'Pengelolaan Museum', code: 'RT2' },
      { name: 'Pendaftaran Museum', code: 'RT2.1' },
      { name: 'Pelindungan Museum', code: 'RT2.2' },
      { name: 'Pengembangan dan Pemanfaatan Museum', code: 'RT2.3' },
    ],
  },
  {
    category: 'Sistem Informasi (TI)',
    items: [
      { name: 'Aplikasi', code: 'TI1.1' },
      { name: 'Aplikasi Umum', code: 'TI1.1.1' },
      { name: 'Jaringan Komunikasi', code: 'TI1.2' },
      { name: 'Jaringan Internet dan Ekstranet', code: 'TI1.2.1' },
      { name: 'Jaringan Intranet', code: 'TI1.2.2' },
      { name: 'Pengelolaan Sistem Kolaborasi', code: 'TI1.2.3' },
      { name: 'Operasional Basis Data', code: 'TI1.3.1' },
      { name: 'Penyajian Data', code: 'TI1.3.2' },
      { name: 'Sistem Layanan Data', code: 'TI1.3.3' },
      { name: 'Web Service (API)', code: 'TI1.3.4' },
      { name: 'Server', code: 'TI1.4' },
      { name: 'Server Virtual', code: 'TI1.4.2' },
      { name: 'Tata Kelola TIK', code: 'TI2' },
      { name: 'Layanan TIK', code: 'TI2.1' },
      { name: 'Perencanaan, Monitoring dan Evaluasi Layanan TIK', code: 'TI2.1.1' },
      { name: 'Tingkat Layanan TIK', code: 'TI2.1.2' },
      { name: 'Keamanan Informasi', code: 'TI2.2' },
      { name: 'Pengelolaan Keamanan Informasi', code: 'TI2.2.1' },
      { name: 'Pengendalian Keamanan Informasi', code: 'TI2.2.2' },
    ],
  },
];